protected/controllers/ArticleController.php
<?php

class ArticleController extends Controller
{
	//~ const TYPE_BUG=0;
	//~ const TYPE_FEATURE=1;
	//~ const TYPE_TASK=2;
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**	
 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','view', 'search', 'update','add', 'detail'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','add','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	/**
	 * Displays a particular detail of this model
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionDetail($id)
	{
		$this->render('detail',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Article;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		 if(isset($_POST['Article']))
		{
			$model->attributes=$_POST['Article'];
			if($model->save())
                         Yii::app()->user->setFlash('success', "<strong>Created!</strong> Article Created Successfull");
                         $this->redirect(array('index'));
		}
                $model->publish=1;
		$this->render('create',array(
			'model'=>$model,
		));
	}
        /**
        * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the category to be pre-populated
         * 
         */
	public function actionAdd($id)
	{
		$model=new Article;
                if(isset($_POST['Article']))
		{
			$model->attributes=$_POST['Article'];
			if($model->save())
                         Yii::app()->user->setFlash('success', "Article Created");
                         $this->redirect(array('add','id'=>$id));
		}
                $model->category_id=$id;
		$model->publish=1;

		$this->render('create',array(
			'model'=>$model,
		));
	}
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Article']))
		{
			$model->attributes=$_POST['Article'];
			if($model->save())
                              Yii::app()->user->setFlash('success', "Article Saved");
				$this->redirect(array('index','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{	
		
             // provide grid search functionality
            $filter = new Article('search');
            $filter->attachBehavior('remember-filter', array(
               'class' => 'application.models.behaviors.ERememberFiltersBehavior',
           ));
            //$dataProvider=new CActiveDataProvider('Article');
            $dataProvider = new ActiveDataProvider('Article', array(
           'criteria' => array(
                //'condition' => 'publish=1',
                'with' => array('categories'),// => array(
                       // 'with' => 'priceBreakdown'
                   // )),
            ),
            'pagination' => array('pageSize' => 100)
             ));
            // search function has to return cdbcriteria instead of data provider
             $filter->filterDataProvider($dataProvider);
         
            //d($_GET);
		$this->render('index',array(
                    'dataProvider'=>$dataProvider,
                    'filter' => $filter
		));
	}
	
	/**
	 * Search models.
	 */
	public function actionSearch()
	{	
			$state= user()->getStateId();
             // provide grid search functionality
            $filter = new Article('search');
           $state= user()->getStateId();// d($_GET);
            if (isset($_GET['Article'])) {
				$vars=$_GET['Article'];
					$filter->globalSearch=$vars['globalSearch'];
					d('here',$vars['globalSearch']);
			}
            $filter->attachBehavior('remember-filter', array(
               'class' => 'application.models.behaviors.ERememberFiltersBehavior',
           ));
            //$dataProvider=new CActiveDataProvider('Article');
            $dataProvider = new ActiveDataProvider('Article', array(
           'criteria' => array(
                 
                'with' => array(
                    'categories' => array(
                        //'together' => true,
                       
                        'condition' =>  'state_id = '. $state,
                        
                    ),
                
				)),
				'pagination' => array('pageSize' => 100)
             ));
            // search function has to return cdbcriteria instead of data provider
             $filter->filterDataProvider($dataProvider);
         
            //
		$this->render('search',array(
                    'dataProvider'=>$dataProvider,
                    'filter' => $filter
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Article('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Article']))
			$model->attributes=$_GET['Article'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Article::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='article-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	/* 
	 * getArticleCategory
	 * */
	//~ public function getCategoryOptions()
	//~ {
		//~ 
		//~ 
		//~ $categoryArray= CHtml::listData(Article_Category::model()->findAll(), 'cat_id', 'name'); 
		//~ return $categoryArray;
		//~ 
	//~ }
	//~ public function getArticle()
	//~ {
		//~ return $this->_article;
	//~ }
	public function getTypeOptions() 
	{
		return array(
		  self::TYPE_BUG=>'Bug',
		  self::TYPE_FEATURE=>'Feature',
		  self::TYPE_TASK=>'Task',
		);
	}
	
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2-bu.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>another link could go here...
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
    <div class="span9">
        <div id="content">
            <?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>
            <?php echo $content; ?>
        </div><!-- content -->
    </div>
    <div class="span3"   style="margin-top:1px;">
        <div id="sidebar">
            <?php
            if (user()->isAdmin()) {
                $this->beginWidget('zii.widgets.CPortlet', array(
                    'title' => 'Operations',
                ));
                $this->widget('bootstrap.widgets.TbMenu', array(
                    'items' => $this->menu,
                    'htmlOptions' => array('class' => 'operations'),
                ));
                $this->endWidget();
            }
            if (!user()->isGuest) {
                //echo "list categories<br />";	 
                //echo user()->name;
                $state = user()->getStateId();
                //echo "state " . $state;
                if ($state > 0) {
                    $dataProvider = new CActiveDataProvider('Article_Category', array(
                        'criteria' => array(
                            'condition' => "t.state_id=" . $state
                        ),
                        //sort should be by rfg category i think?
                        'sort' => array(
                            'defaultOrder' => 't.priority ASC'
                        ),
                        'pagination' => array('pageSize' => 100)
                    ));
                    $dataProvider = new CActiveDataProvider('Article_Category');
                    $this->renderPartial('/layouts/sidebar', array(
                        'model' => $dataProvider,
                    ));
                }
            }
            ?>
        </div><!-- sidebar -->
    </div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main-bu.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				//array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by Mariposa Publishing.<br/>
		All Rights Reserved.<br/>
		
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->baseUrl;//echo Yii::app()->theme->baseUrl; ?>/css/styles.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>

	<?php Yii::app()->bootstrap->register(); ?>
</head>

<body>
<?php

        $this->renderPartial('//layouts/main_menu');

/*
 * $this->widget('bootstrap.widgets.TbNavbar',array(
    'items'=>array(
        array(
            'class'=>'bootstrap.widgets.TbMenu',
            'items'=>array(
                array('label'=>'Home', 'url'=>array('/site/index')),
                array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
                array('label'=>'Contact', 'url'=>array('/site/contact')),
                array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
                array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
            ),
        ),
    ),
)); 
*/ 
?>

<div class="container" id="page">

	

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer" style="clear:both;">
		Copyright &copy; <?php echo date('Y'); ?> by Mariposa.<br/>
		All Rights Reserved.<br/>
		
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/layouts/main_menu.php
<?php

// it might be cached with dependency based on active role

//~ if ($activeRole == null) {
    //~ $companySettings = null;
//~ } else if ($activeRole['connected_to'] == 'copacker') {
    //~ // TODO: cache company name together with active role in session
    //~ $companySettings = array('label' => 'Company Profile', 'url' => array('copacker/settings'));
//~ } else if ($activeRole['connected_to'] == 'connector') {
    //~ $companySettings = array('label' => 'Company Profile', 'url' => array('connector/settings'));
//~ } else if ($activeRole['connected_to'] == 'food_monitor') {
    //~ $companySettings = array('label' => 'Company Profile', 'url' => array('foodMonitor/settings'));
//~ }  else if ($activeRole['connected_to'] == 'picknpack') {
    //~ $companySettings = array('label' => 'Company Profile', 'url' => array('picknpack/settings'));
//}
//d($activeRole['connected_to'] . "ddd");


$this->widget('bootstrap.widgets.TbNavbar', array(
     'collapse' => true,
              'fluid' => false,
            'fixed' => false,
    'items' => array(
        array(
            'class' => 'bootstrap.widgets.TbMenu',
             
            'items' => array(
                array('label' => 'Home', 'url' => array('/site/index')),
                
                array('label' => 'Articles', 'url' => url('/Article'), 'visible' => user()->isAdmin()),
				array('label' => 'Categories', 'url' => url('/Category'), 'visible' => user()->isAdmin()),
				array('label' => 'Users', 'url' => url('/User'), 'visible' => user()->isAdmin()),
				array('label' => 'Attorneys', 'url' => url('/Attorney'), 'visible' => user()->isAdmin()),
				array('label'=>'Search', 'url'=>array('/article/search'),'visible' => !user()->isGuest),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
                array('label' => 'Login', 'url' => array('site/login'), 'visible' => Yii::app()->user->isGuest),
                //array('label' => 'Settings', 'visible' => !user()->isGuest, 'items' => array(
                       
                //        array('label' => 'User Profile', 'url' => array('/user/settings')),
                //        array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'))
                //    )),
                array('label' => 'Logout', 'visible' => !user()->isGuest, 'url' => array('/site/logout'))
            ),
        ),
    ),
));


?>

protected/views/layouts/sidebar.php
<address>
Mariposa Publishing<br />
PO Box 578<br />
Willernie, MN 55090<br />
	(651) 773-5230<br />
</address>
<?php 
//var_dump($model);
//temp
$state= user()->getStateId();
$list=Article_Category::model()->getCategoryList($state, false);
//~ print_r($list);
echo "<ul id='cat_side'>";
foreach ($list as $key => $value) {
	
	echo "<li>" . CHtml::link($value, url('/Category/list/'. $key))    . "</li>";
}
echo "</ul>";
?>